wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/brain2brain/__main__.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
activation:
  desc: null
  value: linear
batch_size:
  desc: null
  value: 2048
debug_mode:
  desc: null
  value: false
delay_pred:
  desc: null
  value: 2
dropout_rate:
  desc: null
  value: 0.05
electrode_out:
  desc: null
  value: 2
electrode_selection:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
epochs:
  desc: null
  value: 128
experiment_description:
  desc: null
  value: Experiment M2O GRU Bin Norm - Sequential 2
experiment_name:
  desc: null
  value: gru_m2o_bin_norm_seq_2
hidden_units:
  desc: null
  value: 5
length_pred:
  desc: null
  value: 1
lookback_window:
  desc: null
  value: 5
loss:
  desc: null
  value: mae
opt:
  desc: null
  value: RMSprop
path:
  desc: null
  value: /home/tmarcu/brain2brain/brain2brain/train_676_bin_norm_files_projects.txt
recurrent_dropout:
  desc: null
  value: 0.05
return_sequences:
  desc: null
  value: true
samples_per_second:
  desc: null
  value: 1
target_folder:
  desc: null
  value: gru_m2o_bin_norm_seq_2/
